name: my_lyric
description: A Flutter package to encode and decode lrc.
version: 0.3.0
homepage: https://github.com/coolight7/my_lyric

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  my_util_base:
  my_string_util: 
  html_unescape_xx: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec