name: lyric_xx
description: A Flutter package to encode and decode lrc.
version: 0.5.0
homepage: https://github.com/coolight7/lyric_xx

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  util_xx: ^0.2.0
  string_util_xx: ^0.2.1
  html_unescape_xx: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec