name: lyric_xx
description: A Flutter package to encode and decode lrc.
version: 0.7.4
homepage: https://github.com/coolight7/lyric_xx

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  util_xx: ^0.2.1
  string_util_xx: ^0.2.2
  html_unescape_xx: 

dev_dependencies:
  test:
  lints: